[project]
name = "ugg-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "curl-cffi>=0.14.0",
    "dacite>=1.9.2",
    "pandas>=3.0.1",
    "typer>=0.24.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.15.7",
    "ty>=0.0.25",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
check_untyped_defs = true
disallow_any_expr = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
extra_checks = true
no_implicit_reexport = true
strict_equality = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ty.analysis]
respect-type-ignore-comments = false
